directorio_docente/directorio_docente/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name="home"),
    path('docentes/', include(('gestion_docentes.urls', 'gestion_docentes'), namespace='gestion_docentes')),
    #path('materias/', include(('gestion_materias.urls', 'gestion_materias'), namespace='gestion_materias')),
]

directorio_docente/gestion_docentes/urls.py
from django.urls import path
from .views import lista_docentes

urlpatterns = [
    path('', lista_docentes, name='lista'),
]

directorio_docente/gestion_materias/models.py
from django.db import models

# Create your models here.

directorio_docente/directorio_docente/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

directorio_docente/gestion_docentes/views.py
from django.shortcuts import render

def lista_docentes(request):
    return render(request, 'gestion_docentes/lista.html')

directorio_docente/gestion_materias/views.py
from django.shortcuts import render

# Create your views here.

directorio_docente/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Directorio Docente</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block others_css %}{% endblock %}
</head>
<body>
    <header class="header">
        <h1>Directorio Docente</h1>
        <nav class="nav">
            <ul>
                <li class="boton"><a href="{% url 'home' %}">Home</a></li>
                <li class="boton"><a href="{% url 'gestion_docentes:lista' %}">Docentes</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>© 2025 Directorio Docente.</p>
    </footer>
</body>
</html>

directorio_docente/templates/gestion_docentes/lista.html
{% extends "base.html" %}

{% block title %}Lista de Docentes{% endblock %}

{% block content %}
    <h2>Lista de Docentes</h2>
    <ul>
        <li>Pepe</li>
        <li>Manolo</li>
        <li>Paco</li>
    </ul>
{% endblock %}

directorio_docente/templates/home.html
{% extends "base.html" %}

{% block title %}Inicio{% endblock %}
{% load static %}
{% block others_css %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="home-container">
    <h2>Inicio</h2>
    <p>Bienvenido a nuestra página de inicio.</p>
</div>
{% endblock %}